AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Part-9 - Configures application auto-scaling policies for Fargate tasks."

Parameters:
  ECSClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ECSCluster/ECS/ClusterName
    Description: "The Name of the ECS Cluster"

  ECSServiceName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ECSCluster/ECS/ServiceName
    Description: "he Name of the ECS Service"

  Stage:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ECSCluster/StageName
    Description: "The Name of the environment."

Resources:
  ### ECS Auto Scaling ###
  ECSAutoScalingScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 5  # Maximum number of tasks
      MinCapacity: 1  # Minimum number of tasks
      ResourceId: !Sub "service/${ECSClusterName}/${ECSServiceName}"
      RoleARN: !GetAtt AutoScalingRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ECSAutoScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ECSServiceAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ECSAutoScalingScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 50.0      # Target CPU utilization percentage
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 300   # Cooldown in seconds after a scale-in event
        ScaleOutCooldown: 300  # Cooldown in seconds after a scale-out event

  ### IAM Role for Auto Scaling ###
  AutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - sts:AssumeRole
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/Protect-Me" # Attach the required boundary
      Policies:
        - PolicyName: AutoScalingPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                  - cloudwatch:DescribeAlarms
                  - application-autoscaling:RegisterScalableTarget
                  - application-autoscaling:PutScalingPolicy
                  - application-autoscaling:DescribeScalingPolicies
                  - application-autoscaling:DescribeScalableTargets
                  - ecs:DescribeServices
                  - ecs:UpdateService
                Resource: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/${ECSServiceName}"
