AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Part-7 - Provisions the ECS Cluster for running serverless containerized applications."

Parameters:
  VPCID:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ECSCluster/VPC/VPCID
    Description: "The ID of the existing VPC."

  ALBSecurityGroupID:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ECSCluster/ALB/SecurityGroupID
    Description: "The ID of the Security Group of the ALB"

  ECSClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ECSCluster/ECS/ClusterName
    Description: "The Name of the ECS Cluster"

  Stage:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ECSCluster/StageName
    Description: "The Name of the environment."

Resources:
  ### ECS Components ###
  ### Step 1️⃣: Create a Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterName
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      ServiceConnectDefaults:
        Namespace: my-service.local
      Tags:
        - Key: Name
          Value: !Ref ECSClusterName
        - Key: Environment
          Value: !Ref Stage
        - Key: Where
          Value: !Ref "AWS::Region"
        - Key: For
          Value: Education
        - Key: System
          Value: ECSCluster

  ### Security Group for Fargate Tasks ###
  FargateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Fargate tasks
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref ALBSecurityGroupID # Only ALB can send traffic
          #SourceSecurityGroupName: !Ref ALBSecurityGroupName # Only ALB can send traffic
      Tags:
        - Key: Name
          Value: FargateSecurityGroup
        - Key: Environment
          Value: !Ref Stage
        - Key: Where
          Value: !Ref "AWS::Region"
        - Key: For
          Value: Education
        - Key: System
          Value: ECSCluster

Outputs:
  ECSClusterARN:
    Description: ARN of the ECS Cluster
    Value: !GetAtt ECSCluster.Arn

  FargateSecurityGroupID:
    Description: The ID of SecurityGroup for Fargate within Private Subnets
    Value: !Ref FargateSecurityGroup