AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Part-4 - Enables VPC Flow Logs for monitoring network traffic."

Parameters:
  VPCID:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ECSCluster/VPC/VPCID
    Description: "The ID of the existing VPC."
  Stage:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ECSCluster/StageName
    Description: "The Name of the environment."

Resources:
  ### VPC Flow Logs ###
  VPCFlowLogs:
    Type: AWS::EC2::FlowLog
    Properties:
      ResourceId: !Ref VPCID
      ResourceType: VPC
      TrafficType: ALL # Capture ACCEPT, REJECT, and ALL traffic
      LogDestinationType: cloud-watch-logs
      LogDestination: !GetAtt VPCFlowLogGroup.Arn
      DeliverLogsPermissionArn: !GetAtt VPCFlowLogRole.Arn

  ### CloudWatch Log Group for VPC Flow Logs ###
  VPCFlowLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/VPC/ECSCluster/${Stage}/FlowLogs"
      RetentionInDays: 1 # Retain logs for n days

  ### IAM Role for VPC Flow Logs ###
  VPCFlowLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - vpc-flow-logs.amazonaws.com
            Action:
              - sts:AssumeRole
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/Something" # Attach the required boundary
      Policies:
        - PolicyName: FlowLogPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/VPC/ECSCluster/${Stage}/FlowLogs/${AWS::StackName}:*"

Outputs:
  ### VPC Flow Logs ###
  VPCFlowLogGroupName:
    Description: "CloudWatch Log Group Name for VPC Flow Logs"
    Value: !Ref VPCFlowLogGroup

  VPCFlowLogsID:
    Description: "VPC Flow Logs ID (Logs network traffic for security & monitoring)"
    Value: !Ref VPCFlowLogs

  ### ⚠️ Cost Warnings ###
  VPCFlowLogsCostWarning:
    Description: "⚠️ VPC Flow Logs incur charges based on the amount of logged data! 📊 Monitor usage."
    Value: "VPC Flow Logs are enabled. Ensure retention & logging policies align with your budget."