AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Part-1 - Stores key infrastructure parameters (e.g., VPC, networking, ALB, and ECS settings) in AWS Systems Manager (SSM) Parameter Store."

Parameters:
  VPCName:
    Type: String
    Default: TS-VPC
    Description: "The logical name of the VPC."

  VPCID:
    Type: String
    Default: Unknown-vpc-xxxx-300-takeout-coffees-later
    Description: "The unique ID of the VPC where resources will be deployed."

  PublicSubnet1:
    Type: String
    Default: Unknown-subnet-xxxa-300-takeout-coffees-later
    Description: "The first public subnet ID (e.g., for NAT Gateway or ALB if required)."

  PublicSubnet2:
    Type: String
    Default: Unknown-subnet-xxxb-300-takeout-coffees-later
    Description: "The second public subnet ID (e.g., for NAT Gateway or ALB if required)."

  PrivateSubnet1:
    Type: String
    Default: Unknown-subnet-xxxc-300-takeout-coffees-later
    Description: "The first private subnet ID (e.g., for ECS tasks, databases, or internal workloads)."

  PrivateSubnet2:
    Type: String
    Default: Unknown-subnet-xxxd-300-takeout-coffees-later
    Description: "The second private subnet ID (e.g., for ECS tasks, databases, or internal workloads)."

  AvailabilityZones:
    Type: String
    Default: us-west-2a,us-west-2b,us-west-2c,us-west-2d
    Description: "A list of Availability Zones (AZs) to distribute resources across multiple fault domains."

  ACMCertificateArn:
    Type: String
    Default: Unknown-ACM-ARN-300-takeout-coffees-later
    Description: "The Amazon Resource Name (ARN) of the ACM certificate for securing HTTPS connections."

  ALBSecurityGroupID:
    Type: String
    Default: Unknown-ALB-SGName-300-takeout-coffees-later
    Description: "The security group ID assigned to the Application Load Balancer and Fagate's security group (must be updated after deployment)."

  ALBTargetGroupARN:
    Type: String
    Default: Unknown-ALB-TGARN-300-takeout-coffees-later
    Description: "The Amazon Resource Name (ARN) of the ALB target group (must be updated after deployment)."

  ALBName:
    Type: String
    Default: TS-ALB
    Description: "The logical name of the Application Load Balancer (ALB)."

  ALBS3BucketName:
    Type: String
    Default: Unknown-alb-logs-300-takeout-coffees-later
    Description: "The S3 bucket where ALB access logs will be stored."

  ALBPrefix:
    Type: String
    Default: alb-access-logs
    Description: "The prefix used for ALB access log files in the S3 bucket."

  ECSClusterName:
    Type: String
    Default: TS-ECS-Cluster
    Description: "The logical name of the ECS cluster."

  ECSServiceName:
    Type: String
    Default: TS-ECS-Service
    Description: "The logical name of the ECS service."

  ECSTaskDefinitionName:
    Type: String
    Default: TS-11
    Description: "The task definition name for the ECS service."

  ECSContainerName:
    Type: String
    Default: TTPD-nginx
    Description: "The container name inside the ECS task definition."

  ECSContainerImageName:
    Type: String
    Default: Unknown-ECS-Container-ImageName-300-takeout-coffees-later
    Description: "The image name used by the ECS container (must be updated after image creation)."

  ECRRepoName:
    Type: String
    Default: debut
    Description: "The Amazon Elastic Container Registry (ECR) repository name for storing container images."

  StageName:
    Type: String
    Default: Test
    Description: "The environment name (e.g., Test, Staging, Production)."

Resources:
  VPCNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/VPC/VPCName
      Type: String
      Value: !Ref VPCName
      Description: "The VPC's logical name."

  VPCSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/VPC/VPCID
      Type: String
      Value: !Ref VPCID
      Description: "The VPC ID. (update after deployment if necessary)."

  PublicSubnet1SSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/VPC/PublicSubnet1
      Type: String
      Value: !Ref PublicSubnet1
      Description: "The first public subnet ID. (update after deployment if necessary)."

  PublicSubnet2SSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/VPC/PublicSubnet2
      Type: String
      Value: !Ref PublicSubnet2
      Description: "The second public subnet ID. (update after deployment if necessary)."

  PrivateSubnet1SSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/VPC/PrivateSubnet1
      Type: String
      Value: !Ref PrivateSubnet1
      Description: "The first private subnet ID. (update after deployment if necessary)."

  PrivateSubnet2SSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/VPC/PrivateSubnet2
      Type: String
      Value: !Ref PrivateSubnet2
      Description: "The second private subnet ID. (update after deployment if necessary)."

  AvailabilityZonesSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/VPC/AvailabilityZones
      Type: StringList
      Value: !Ref AvailabilityZones
      Description: "The list of Availability Zones."

  ACMCertificateArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ACMCertificateArn
      Type: String
      Value: !Ref ACMCertificateArn
      Description: "The ACM certificate ARN. (update after deployment if necessary)."

  ALBSecurityGroupIDSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ALB/SecurityGroupID
      Type: String
      Value: !Ref ALBSecurityGroupID
      Description: "The security group name of the ALB (update after deployment if necessary)."

  ALBTargetGroupArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ALB/TargetGroupARN
      Type: String
      Value: !Ref ALBTargetGroupARN
      Description: "The ALB Target Group ARN (update after deployment if necessary)."

  ALBNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ALB/ALBName
      Type: String
      Value: !Ref ALBName
      Description: "The ALB Name."

  ALBS3BucketSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ALB/S3BucketName
      Type: String
      Value: !Ref ALBS3BucketName
      Description: "The ALB log storage S3 bucket name. (update after deployment if necessary)."

  ALBPrefixSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ALB/ALBPrefix
      Type: String
      Value: !Ref ALBPrefix
      Description: "The ALB log prefix in the S3 bucket."

  ECSClusterNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ECS/ClusterName
      Type: String
      Value: !Ref ECSClusterName
      Description: "The ECS cluster name."

  ECSServiceNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ECS/ServiceName
      Type: String
      Value: !Ref ECSServiceName
      Description: "The ECS service name."

  ECSTaskDefinitionNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ECS/TaskDefinitionName
      Type: String
      Value: !Ref ECSTaskDefinitionName
      Description: "The ECS task definition name."

  ECSContainerNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ECS/ContainerName
      Type: String
      Value: !Ref ECSContainerName
      Description: "The container name inside the ECS task definition."

  ECSContainerImageNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ECS/ContainerImageName
      Type: String
      Value: !Ref ECSContainerImageName
      Description: "The ECS container image name. (update after deployment if necessary)."

  ECRRepoNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/ECR/RepoName
      Type: String
      Value: !Ref ECRRepoName
      Description: "The ECR repository name."

  StageNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /FargateCluster/StageName
      Type: String
      Value: !Ref StageName
      Description: "The environment stage name."

Outputs:
  VPCName:
    Description: "SSM Parameter storing the VPC's logical name."
    Value: !Ref VPCNameSSM

  VPC:
    Description: "SSM Parameter storing the VPC ID. (Temporary value)"
    Value: !Ref VPCSSM

  PublicSubnet1:
    Description: "SSM Parameter storing the first public subnet ID. (Temporary value)"
    Value: !Ref PublicSubnet1SSM

  PublicSubnet2:
    Description: "SSM Parameter storing the second public subnet ID. (Temporary value)"
    Value: !Ref PublicSubnet2SSM

  PrivateSubnet1:
    Description: "SSM Parameter storing the first private subnet ID. (Temporary value)"
    Value: !Ref PrivateSubnet1SSM

  PrivateSubnet2:
    Description: "SSM Parameter storing the second private subnet ID. (Temporary value)"
    Value: !Ref PrivateSubnet2SSM

  AvailabilityZones:
    Description: "SSM Parameter storing the list of Availability Zones."
    Value: !Ref AvailabilityZonesSSM

  ACMCertificateArn:
    Description: "SSM Parameter storing the ACM certificate ARN."
    Value: !Ref ACMCertificateArnSSM

  ALBSecurityGroupID:
    Description: "SSM Parameter storing the security group name of the ALB. (Temporary value)"
    Value: !Ref ALBSecurityGroupIDSSM

  ALBTargetGroupARN:
    Description: "SSM Parameter storing the ALB Target Group ARN. (Temporary value)"
    Value: !Ref ALBTargetGroupArnSSM

  ALBName:
    Description: "SSM Parameter storing the ALB Name."
    Value: !Ref ALBNameSSM

  ALBS3BucketName:
    Description: "SSM Parameter storing the ALB log storage S3 bucket name. (Temporary value)"
    Value: !Ref ALBS3BucketSSM

  ALBPrefix:
    Description: "SSM Parameter storing the ALB log prefix in the S3 bucket."
    Value: !Ref ALBPrefixSSM

  ECSClusterName:
    Description: "SSM Parameter storing the ECS cluster name."
    Value: !Ref ECSClusterNameSSM

  ECSServiceName:
    Description: "SSM Parameter storing the ECS service name."
    Value: !Ref ECSServiceNameSSM

  ECSTaskDefinitionName:
    Description: "SSM Parameter storing the ECS task definition name."
    Value: !Ref ECSTaskDefinitionNameSSM

  ECSContainerName:
    Description: "SSM Parameter storing the container name inside the ECS task definition."
    Value: !Ref ECSContainerNameSSM

  ECSContainerImageName:
    Description: "SSM Parameter storing the ECS container image name. (Temporary value)"
    Value: !Ref ECSContainerImageNameSSM

  ECRRepoName:
    Description: "SSM Parameter storing the ECR repository name."
    Value: !Ref ECRRepoNameSSM

  StageName:
    Description: "SSM Parameter storing the environment stage name."
    Value: !Ref StageNameSSM